### ISSUE TITLE
Multiple inverters support in all plugins

### ISSUE THREAD

**Issue by XtheOne** [XtheOne/Inverter-Data-Logger#1]
Current state is that it is only implemented for domoticz.
Other plugins will follow.

**Comment by XtheOne** [comment]
PVOutput is updated.
Now you can define apikey and sysid for every inverter.
So multiple accounts or one donation account can be used for multiple inverters.
ScanLoggers can be used to detect the Logger(s) and Inverter(s) on your local network.

**Comment by XtheOne** [comment]
Should work now

**Comment by kajhoej** [comment]
I have 2 inverters connected and use the mqtt plugin but I cannot separate the 2 inverters in the mqtt output as they have the same subject. Shouldnt the inverters serial number be part of the subject in the mqtt message?

**Comment by XtheOne** [comment]
Well, the mqqt plugin was written by someone else.
I can change the script in several ways.

I can change "power/solar/e_total" to "solar/<ID>/e_total" so inserting the inverter SN into the message path.
Or make separate entries in the config file like it is done for Domoticz and them make the publish path prefix configurable.
So what would you prefer?

**Comment by XtheOne** [comment]
I can change this in 2 ways.
Change "power/solar/..." to "solar/<ID>/..."
Or make separate entries in the config file like the domoticz plugin. You could then select separate mqqt servers & paths.

**Comment by XtheOne** [comment]
Multiple inverters support added in mqtt
