### ISSUE TITLE
Usage of CSV file with jsunnyreports

### ISSUE THREAD

**Issue by ervee** [XtheOne/Inverter-Data-Logger#14]
Hi!

I'm successfully using your application to pull data from my Omnik and store the CSV output in a unique file every 1 minute. But I'm unable to load the CSV files into jsunnyreports (http://www.jsunnyreports.com/). Problem is, I don't know what values jsunnyreports is expecting at what position in the file... Perhaps you have experience with this?

I also contacted the creator of jsunnyreports and awaiting response. Perhaps more people have issues with this so this issue would perhaps also help other people once we figure this out and post results here.

Thank you.
Ralf.

**Comment by Jendemen** [comment]
Hi ervee,

How did you manage to get the CSV output?
Store data to MySQL is working, but I prefer the CSV output.

Thanks in advance, Jan

**Comment by XtheOne** [comment]
Enable the CSVOutput plugin.

**Comment by Jendemen** [comment]
Of course I enabled the CSVOutout plugin, but no data.
Using the CSVOutput2file is working now! Thanks.

For my other inverter (SMA) I use SBFspot, which creates a daily csv file and (hopefully) als a month totals csv file. CSVOutput2file is only using 1 file and constantly adding new data to it?

**Comment by XtheOne** [comment]
Yes, only one file. No logic yet to create daily files.
Since no data is stored no monthly stats are possible.
Use Domoticz export or SQL and extract your own tables.

**Comment by XtheOne** [comment]
Added option to create a daily CSV file.
Update your config file.

**Comment by Jendemen** [comment]
GREAT!  I will have a look.  Thanks again.

**Comment by XtheOne** [comment]
One last note, CSVOutout plugin outputs the data to the console, not a file...
