### ISSUE TITLE
PVOutput random average values

### ISSUE THREAD

**Issue by Jendemen** [XtheOne/Inverter-Data-Logger#18]
Updating the data to PVoutput show irregular average values of 1200W. I am using the latest version.
![2018-04-16_12-49-34](https://user-images.githubusercontent.com/34129745/38805211-5135acae-4175-11e8-99e1-2a3934e26829.jpg)
![2018-04-16_12-50-03](https://user-images.githubusercontent.com/34129745/38805217-574a95d2-4175-11e8-926a-d198027cc68e.jpg)

**Comment by XtheOne** [comment]
I checked and now I see what is happening.
Check e_today in the logs what the increment is.
In this case it seems to be 0.1 kWh while the Omnik has 0.01kWh increments. (I get 0/120W as Average)
