### ISSUE TITLE
Add Listen Server

### ISSUE THREAD

**Issue by XtheOne** [XtheOne/Inverter-Data-Logger#19]
Add a server script so that a 2nd server can be defined in the logger itself.

**Comment by XtheOne** [comment]
New script added.
InverterServer.py

**Comment by XtheOne** [comment]
It works and no tester reported any problems so closing this one.

**Comment by conradhagemans** [comment]
Need some help. Script works fine. I have output to MySQL, MQTT and PVOUTPUT.
How can I run this script on my Ubuntu 18.04 server at startup?
I know I have to create a script file in the /etc/systemd/system folder
Will the InverterServer.py script find the config file?
Has someone a sample startup script?
Thanks.
